### ISSUE TITLE
ImportError: No module named face_recognition

### ISSUE THREAD

**Issue by wangxiao5791509** [hai046/Face-Aging-CAAE_pro#1]
Hi, thanks for the code. However, I found the errors as follows: 
ImportError: No module named face_recognition

would you please check the files again? Maybe it indeed does not contain this file.

**Comment by hai046** [comment]
python import 
```
import face_recognition
```

so you can use 
```
pip3/pip  install face_recognition
```

[face_recognition](https://github.com/ageitgey/face_recognition)

**Comment by hai046** [comment]
@wangxiao5791509 
As well ，no matter how I improve，the result also is not good  .
Someone  have same question at the original author project issue    https://github.com/ZZUTK/Face-Aging-CAAE/issues/11


If you solve it, hope you can share it ，thanks!

**Comment by wangxiao5791509** [comment]
Thanks for the code. Actually, I also tried that code, but I got model collapse. It only shown me the yellow background image, but no face at al. I give up that code, and try to replement with pytorch again.

**Comment by wangxiao5791509** [comment]
@hai046
